### ISSUE TITLE
Website layout

### ISSUE THREAD

**Issue by nothingismagick** [webview/docs#1]
The proper website layout is likely to be a complex decision, and something we should put some deep thought into. Ideally we would enable:

1. versioning
2. translations
3. core documentation
4. bindings documentation
5. organisational documentation

@laegel has some experience with docusaurus - and proposed subdomains for the bindings. let's discuss how we want to do this and try to get it right from the very beginning.

**Comment by paulocoghi** [comment]
https://github.com/webview/webview/issues/670

**Comment by nicklasfrahm** [comment]
Looking at the requirements @nothingismagick presented, I think we might _cut the elephant into pieces_ by first setting up [mkdocs-material](https://squidfunk.github.io/mkdocs-material/). From a quick glimpse at its docs, it does support the following features:

- [x] [Versioning](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/)
- [x] [Internationalization](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/)

In addition, I believe that this theme offers great options to make the documentation more accessible as it allows more fine-grained configuration of navigation and menus.

I will submit a PR, which sets up the theme. I will for now not focus on the implementation of either of the aforementioned features.

**Comment by paulocoghi** [comment]
@nicklasfrahm I suggest to clone the docs part from the Autopilot repo (`site` folder and `mkdocs.yml` file on https://github.com/aws/copilot-cli/)

It already comes with a really good design and organized structure for `mkdocs-material`:

[Main page]

![copilot-website](https://user-images.githubusercontent.com/378397/153829862-808fa0a9-b3ae-4241-a5af-5850775c1a00.png)

[Docs]

![copilot-docs](https://user-images.githubusercontent.com/378397/153829931-f8e42938-cd2c-4d33-948e-f4bbc26f327e.png)
