### ISSUE TITLE
wiki content

### ISSUE THREAD

**Issue by petabyt** [webview/docs#3]
TODO list:
- [ ] Ideal Project Setup (Makefiles, linking)
- [x] Alternatives to webview
- [ ] Link binding pages to existing documentation
- [ ] Page describing the WebView internals (enums, macros)
- [ ] Page describing common WebView API features and quirks

**Comment by nicklasfrahm** [comment]
What about the content from the [webview/meta](https://github.com/webview/meta) repository? Could it be useful to have it living in here as part of the documentation?

**Comment by petabyt** [comment]
Doesn't seem to have a whole lot, what do you think should be moved over?

**Comment by nicklasfrahm** [comment]
I think all of it could live in a `community.md`. The meta repository could then be removed in order to have a single source of truth via the documentation.

**Comment by petabyt** [comment]
Sounds good, feel free to make a pull request
